const franchiseData = {
  marvel: [
    { title: "Captain America: The First Avenger", duration: 124, fact: "The earliest story in MCU chronology." },
    { title: "Captain Marvel", duration: 123, fact: "Set in 1995 with a Blockbuster cameo." },
    { title: "Iron Man", duration: 126, fact: "Started the MCU in 2008." },
    { title: "Iron Man 2", duration: 124, fact: "Introduced Black Widow." },
    { title: "The Incredible Hulk", duration: 112, fact: "Edward Norton played Hulk." },
    { title: "Thor", duration: 115, fact: "Chris Hemsworth’s thunderous debut." },
    { title: "The Avengers", duration: 143, fact: "First major team-up." },
    { title: "Iron Man 3", duration: 130, fact: "Tony deals with PTSD." },
    { title: "Thor: The Dark World", duration: 112, fact: "One of the lower-ranked films." },
    { title: "Captain America: The Winter Soldier", duration: 136, fact: "Political thriller vibes." },
    { title: "Guardians of the Galaxy", duration: 121, fact: "Space opera with killer mixtape." },
    { title: "Guardians of the Galaxy Vol. 2", duration: 136, fact: "Quill meets his dad." },
    { title: "Avengers: Age of Ultron", duration: 141, fact: "Gave us Vision and Wanda." },
    { title: "Ant-Man", duration: 117, fact: "Tiny heist, big heart." },
    { title: "Captain America: Civil War", duration: 147, fact: "Team Cap vs Team Iron Man." },
    { title: "Black Widow", duration: 134, fact: "Long-overdue solo outing." },
    { title: "Black Panther", duration: 134, fact: "Cultural landmark." },
    { title: "Spider-Man: Homecoming", duration: 133, fact: "Tom Holland's full debut." },
    { title: "Doctor Strange", duration: 115, fact: "Time-bending visuals." },
    { title: "Thor: Ragnarok", duration: 130, fact: "Funny, colorful and weird." },
    { title: "Ant-Man and the Wasp", duration: 118, fact: "Set just before Infinity War." },
    { title: "Avengers: Infinity War", duration: 149, fact: "The snap..." },
    { title: "Avengers: Endgame", duration: 181, fact: "Time heist + tearjerker." },
    { title: "WandaVision", duration: 350, fact: "TV sitcom meets multiverse." },
    { title: "The Falcon and the Winter Soldier", duration: 336, fact: "Legacy of the shield." },
    { title: "Loki", duration: 300, fact: "Multiverse mayhem begins." },
    { title: "What If...?", duration: 270, fact: "Alternate realities galore." },
    { title: "Shang-Chi", duration: 132, fact: "Martial arts meets Marvel." },
    { title: "Eternals", duration: 156, fact: "Gods among us." },
    { title: "Spider-Man: Far From Home", duration: 129, fact: "Post-Endgame Europe trip." },
    { title: "Spider-Man: No Way Home", duration: 148, fact: "Multiverse of Spideys." },
    { title: "Doctor Strange 2", duration: 126, fact: "Madness indeed." },
    { title: "Thor: Love and Thunder", duration: 119, fact: "Goats and Gorr." },
    { title: "Black Panther: Wakanda Forever", duration: 161, fact: "A tribute to Chadwick." },
    { title: "Ant-Man and the Wasp: Quantumania", duration: 124, fact: "Quantum Kang-time." },
    { title: "Guardians of the Galaxy Vol. 3", duration: 150, fact: "Rocket’s emotional arc." },
    { title: "The Marvels", duration: 105, fact: "Carol, Kamala, and Monica unite." },
  ],
  bond: [
    { title: "Dr. No", duration: 110, fact: "Bond's first cinematic outing." },
    { title: "From Russia with Love", duration: 115, fact: "Cold War classic." },
    { title: "Goldfinger", duration: 110, fact: "Iconic villain and Aston Martin." },
    { title: "Thunderball", duration: 130, fact: "Underwater action galore." },
    { title: "You Only Live Twice", duration: 117, fact: "Bond fakes his death." },
    { title: "On Her Majesty's Secret Service", duration: 142, fact: "Bond gets married." },
    { title: "Diamonds Are Forever", duration: 120, fact: "Connery returns." },
    { title: "Live and Let Die", duration: 121, fact: "Moore's debut." },
    { title: "The Man with the Golden Gun", duration: 125, fact: "Christopher Lee as Scaramanga." },
    { title: "The Spy Who Loved Me", duration: 125, fact: "Submarines and Jaws." },
    { title: "Moonraker", duration: 126, fact: "Bond in space." },
    { title: "For Your Eyes Only", duration: 127, fact: "Back to basics." },
    { title: "Octopussy", duration: 131, fact: "Clown disguise included." },
    { title: "A View to a Kill", duration: 131, fact: "Walken is the villain." },
    { title: "The Living Daylights", duration: 130, fact: "Dalton's first film." },
    { title: "Licence to Kill", duration: 133, fact: "Grittier revenge tale." },
    { title: "GoldenEye", duration: 130, fact: "Brosnan’s big entrance." },
    { title: "Tomorrow Never Dies", duration: 119, fact: "Media mogul baddie." },
    { title: "The World Is Not Enough", duration: 128, fact: "Nuclear plot." },
    { title: "Die Another Day", duration: 133, fact: "Invisible car." },
    { title: "Casino Royale", duration: 144, fact: "Craig rebooted Bond." },
    { title: "Quantum of Solace", duration: 106, fact: "Direct sequel." },
    { title: "Skyfall", duration: 143, fact: "M’s swan song." },
    { title: "Spectre", duration: 148, fact: "Blofeld returns." },
    { title: "No Time to Die", duration: 163, fact: "Craig’s epic finale." },
  ],
  mi: [
    { title: "Mission: Impossible", duration: 110, fact: "Vault heist and face masks." },
    { title: "Mission: Impossible 2", duration: 123, fact: "John Woo’s style." },
    { title: "Mission: Impossible III", duration: 126, fact: "Philip Seymour Hoffman = chills." },
    { title: "Ghost Protocol", duration: 132, fact: "Burj Khalifa climb." },
    { title: "Rogue Nation", duration: 131, fact: "Underwater stunt madness." },
    { title: "Fallout", duration: 147, fact: "Helicopter showdown." },
    { title: "Dead Reckoning Part 1", duration: 163, fact: "Train-top tension." },
  ],
  f9: [
    { title: "The Fast and the Furious", duration: 106, fact: "Tuna, NOS, and family." },
    { title: "2 Fast 2 Furious", duration: 108, fact: "Ludacris joins the crew." },
    { title: "Fast & Furious", duration: 107, fact: "Letty presumed dead." },
    { title: "Fast Five", duration: 130, fact: "The vault heist." },
    { title: "Fast & Furious 6", duration: 130, fact: "Letty returns." },
    { title: "Tokyo Drift", duration: 104, fact: "Chronologically here." },
    { title: "Furious 7", duration: 137, fact: "Paul Walker’s farewell." },
    { title: "The Fate of the Furious", duration: 136, fact: "Dom goes rogue." },
    { title: "Hobbs & Shaw", duration: 137, fact: "Spinoff action insanity." },
    { title: "F9", duration: 145, fact: "They went to space." },
    { title: "Fast X", duration: 141, fact: "Jason Momoa makes chaos." },
  ],
  disney: [
    { title: "Snow White and the Seven Dwarfs", duration: 83, fact: "The first full-length animated feature." },
    { title: "Cinderella", duration: 74, fact: "Glass slippers and pumpkin carriages." },
    { title: "Sleeping Beauty", duration: 75, fact: "Aurora’s deep nap game is unmatched." },
    { title: "The Little Mermaid", duration: 83, fact: "Ariel traded her voice for legs." },
    { title: "Beauty and the Beast", duration: 84, fact: "First animated film nominated for Best Picture." },
    { title: "Aladdin", duration: 90, fact: "Robin Williams' Genie stole the show." },
    { title: "The Lion King", duration: 88, fact: "Hakuna Matata forever." },
    { title: "Pocahontas", duration: 81, fact: "Colors of the Wind still hits." },
    { title: "Mulan", duration: 88, fact: "Let’s get down to business..." },
    { title: "Tarzan", duration: 88, fact: "Phil Collins went hard on the soundtrack." },
    { title: "The Princess and the Frog", duration: 97, fact: "Tiana brought jazz back." },
    { title: "Tangled", duration: 100, fact: "Rapunzel with attitude." },
    { title: "Frozen", duration: 102, fact: "Do you wanna build a snowman?" },
    { title: "Moana", duration: 107, fact: "You're welcome." },
    { title: "Encanto", duration: 102, fact: "We don’t talk about Bruno..." },
  ],
  pixar: [
    { title: "Toy Story", duration: 81, fact: "The first fully computer-animated film." },
    { title: "A Bug's Life", duration: 95, fact: "Ants vs. grasshoppers." },
    { title: "Toy Story 2", duration: 92, fact: "Jessie’s song = instant feels." },
    { title: "Monsters, Inc.", duration: 92, fact: "Boo is too cute." },
    { title: "Finding Nemo", duration: 100, fact: "Just keep swimming." },
    { title: "The Incredibles", duration: 115, fact: "Superfamily FTW." },
    { title: "Cars", duration: 117, fact: "Ka-chow!" },
    { title: "Ratatouille", duration: 111, fact: "Anyone can cook." },
    { title: "WALL-E", duration: 98, fact: "Silent cinema in space." },
    { title: "Up", duration: 96, fact: "That opening sequence. Oof." },
    { title: "Toy Story 3", duration: 103, fact: "Everyone cried at the incinerator." },
    { title: "Inside Out", duration: 102, fact: "Emotional rollercoaster." },
    { title: "Coco", duration: 105, fact: "Remember meeee 🎶" },
    { title: "Soul", duration: 100, fact: "Jazz and existentialism." },
    { title: "Turning Red", duration: 100, fact: "Giant red panda chaos." },
    { title: "Luca", duration: 95, fact: "Sea monster summer vibes." },
    { title: "Lightyear", duration: 105, fact: "The Buzz origin(ish) story." },
    { title: "Elemental", duration: 101, fact: "Opposites attract — literally." },
  ],
};